theme: jekyll-theme-minimal
title: Kainers Blog
description: Die Beesonderheiten des normalen Tagesablaufs eines Freelancers

<ul>
  {% for post in site.posts %}
    <li>
      <a href="{{ post.url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

![wtf](/assets/kai(2).jpg)
